service: serverlessbuch-skill

frameworkVersion: ">=1.2.0 <2.0.0"

provider:
  name: aws
  runtime: java8
  stage: demo
  region: eu-west-1
  memorySize: 128
  timeout: 5
  deploymentBucket: dasniko.serverless.deployments.${self:provider.region}

package:
  artifact: target/${self:service}.jar

functions:
  skill:
    handler: de.serverlessbuch.alexa.BookSpeechletRequestStreamHandler
    events:
      - alexaSkill
